DROP TABLE IF EXISTS links;

CREATE TABLE links (
       id INTEGER PRIMARY KEY AUTOINCREMENT,
       criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
       link_original TEXT NOT NULL,
       codigo TEXT NOT NULL UNIQUE
);